parrasoft/parrasoft/urls.py
from django.contrib import admin
from django.urls import path

from home import views

# app_name = "home_app"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.landing, name = 'landing_view'),
    path('project/<int:id>/update/', views.update_project, name = 'update_project'),
    path('project/<int:id>', views.detail_project, name = 'detail_project'),
    path('login/', views.login_view, name = 'login_view'),
    path('logout/', views.logout_view, name = 'logout_view'),
]

parrasoft/home/models.py
from django.db import models
from django.conf import settings

class EmployeeProfile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    bio = models.CharField(max_length = 500, blank = True)
    picture = models.CharField(max_length = 50, default = 'unknown.jpg')
    birthdate = models.DateField(auto_now = False, auto_now_add = False, blank = True, null = True)
    phone = models.CharField(max_length = 50, blank = True)

class Project(models.Model):
    name = models.CharField(max_length = 100)
    repo_url = models.CharField(max_length = 100)
    icon = models.CharField(max_length = 50, default = 'blank.png')
    description = models.CharField(max_length = 500)
    leader = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE, related_name = 'lead_projects')
    due_date = models.DateTimeField(auto_now = False, auto_now_add = False)
    team = models.ManyToManyField(settings.AUTH_USER_MODEL)
    created = models.DateTimeField(auto_now_add = True)

class Activity(models.Model):
    project = models.ForeignKey(Project, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    description = models.CharField(max_length = 500)
    deadline = models.DateTimeField(auto_now = False, auto_now_add = False)
    created = models.DateTimeField(auto_now_add = True)

class Task(models.Model):
    activity = models.ForeignKey(Activity, on_delete = models.CASCADE)
    title = models.CharField(max_length = 200)
    completed = models.BooleanField(default = False)
    created = models.DateTimeField(auto_now_add = True)

parrasoft/home/forms.py
from django import forms
from django.contrib.auth import authenticate

from .models import Project

class LoginForm(forms.Form):
    username = forms.CharField(required = True)
    password = forms.CharField(required = True, widget = forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username = username, password = password)

        if not user:
            raise forms.ValidationError('Username or password incorrect')
        elif not user.is_active:
            raise forms.ValidationError('This employee is not active')

        return super(LoginForm, self).clean(*args, **kwargs)

class ProjectForm(forms.ModelForm):
    repo_url = forms.URLField()

    class Meta:
        model = Project
        fields = '__all__'
        widgets = {
            'repo_url': forms.widgets.URLInput(),
            'description': forms.Textarea(attrs = { 'rows': 2 }),
            'leader': forms.widgets.Select(attrs = { 'class': 'ui dropdown search' }),
            'team': forms.widgets.SelectMultiple(attrs = { 'class': 'ui search dropdown' }),
        }

parrasoft/home/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, login, authenticate, get_user_model
from datetime import datetime
from math import floor

from .forms import LoginForm, ProjectForm
from .models import EmployeeProfile, Project, Task

"""--------------------
INDEX LANDING PAGE VIEW
--------------------"""

def landing(request):
    if request.user.is_authenticated:
        return render(request, 'home/dashboard.html', {
            'profiles': EmployeeProfile.objects.all(),
            'projects_n': Project.objects.count(),
            'current_projects': Project.objects.filter(due_date__gte = datetime.now()),
            'completed_n': Project.objects.exclude(activity__task__completed = False).count(),
            'in_progress_n': Project.objects.filter(activity__task__completed = False, due_date__gte = datetime.now()).distinct().count(),
            'overdue_n': Project.objects.filter(activity__task__completed = False, due_date__lt = datetime.now()).distinct().count(),
            'tasks_n': Task.objects.count(),
            'tasks_n_complete': Task.objects.filter(completed = True).count(),
            'tasks_n_pending': Task.objects.filter(completed = False).count(),
        })
    else:
        return render(request, 'home/landing.html', { 'form': LoginForm })

"""------------------
LIST AND DETAIL VIEWS
------------------"""
def detail_project(request, id):
    project = Project.objects.get(id = id)
    percentage = floor(
        Task.objects.filter(activity__project_id = project.id, completed = True).count() /
        Task.objects.filter(activity__project_id = project.id).count() * 100
    )

    return render(request, 'home/detail_project.html', { 'project': project, 'percentage': percentage })

"""----------------------
CREATION AND UPDATE VIEWS
----------------------"""

def update_project(request, id):
    project = Project.objects.get(id = id)

    if request.method == "GET":
        form = ProjectForm(instance = project)
    else:
        form = ProjectForm(request.POST, instance = project)

        if form.is_valid():
            form.save()
            
            return redirect('landing_view')
    return render(request, 'home/update_project.html', { "form": form })

"""----------------------
USER AUTHENTICATION VIEWS
----------------------"""

def login_view(request):
    form = LoginForm(request.POST or None)

    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username = username, password = password)

        login(request, user)
        return redirect('landing_view')
    else:
        return render(request, 'home/landing.html', { 'form': form })

def logout_view(request):
    logout(request)

    return redirect('landing_view')

parrasoft/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" type="text/css" href="{% static 'semantic.min.css' %}">
  {% block css %}{% endblock css %}
  <title>ParraSoft™ | {% block title %}{% endblock title %}</title>
</head>
<body>
  {% block content %}{% endblock content %}

  <script src="{% static 'jquery.min.js' %}"></script>
  <script src="{% static 'semantic.min.js' %}"></script>
  {% block script %}{% endblock script %}
</body>
</html>

parrasoft/templates/components/anon_menu.html
<div class="ui large top menu inverted">
  <div class="ui container">
    <a href="{% url 'landing_view' %}" class="active item">Home</a>
    <a href="#" class="item">About Us</a>
    <a href="#" class="item">Contact</a>
    <a href="#" class="item">Careers</a>

    <div class="right menu">
      <div class="item">
        <a id="login-btn" class="ui button inverted">Employee Dashboard</a>
      </div>
    </div>
  </div>
</div>

parrasoft/templates/components/main_menu.html
{% load static %}

<div class="ui large top menu">
  <div class="ui container">
    <a href="{% url 'landing_view' %}" class="active item">Overview</a>
    <a href="#" class="item">Projects</a>
    <a href="#" class="item">Employees</a>
    <a href="#" class="item">Calendar</a>

    <div class="right menu">
      <div class="ui dropdown item">
        <div class="text">
          <img class="ui right spaced avatar image" src="{% static 'img/avatars/'|add:user.employeeprofile.picture %}">
          {{ user.username }}
        </div>
        <i class="dropdown icon"></i>
        
        <div class="menu">
          <div class="header">{{ user.first_name }} {{ user.last_name }}</div>
          <div class="divider"></div>

          <a href="{% url 'landing_view' %}" class="item"><i class="globe icon"></i> View Profile</a>
          <a href="{% url 'landing_view' %}" class="item"><i class="edit icon"></i> Edit Profile</a>
          <a href="{% url 'landing_view' %}" class="item"><i class="user icon"></i> Account Details</a>
        </div>
      </div>

      <form action="{% url 'logout_view' %}" class="ui form" method="post">
        {% csrf_token %}

        <div class="item">
          <button class="ui negative labeled icon button">
            <i class="power off icon"></i>
            Log Out
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

parrasoft/templates/home/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  {{ user.first_name }} {{ user.last_name }}'s Dashboard
{% endblock title %}

{% block css %}
  <style>
    body {
      background: #F9F9F9;
    }
  </style>
{% endblock css %}

{% block content %}
  {% include 'components/main_menu.html' %}

  <div class="ui container">
    <div class="ui stacked segments">
      <div class="ui segment large header">
        Projects Overview
      </div>

      <div class="ui horizontal segments">
        <div class="ui segment">
          <h2 class="ui header">
            <i class="blue briefcase icon"></i>
            <div class="content">
              {{ projects_n }}
              <div class="sub header">Total projects</div>
            </div>
          </h2>
        </div>
        
        <div class="ui segment">
          <h2 class="ui header">
            <i class="teal check circle icon"></i>
            <div class="content">
              {{ completed_n }}
              <div class="sub header">Completed</div>
            </div>
          </h2>
        </div>

        <div class="ui segment">
          <h2 class="ui header">
            <i class="yellow flag icon"></i>
            <div class="content">
              {{ in_progress_n }}
              <div class="sub header">In Progress</div>
            </div>
          </h2>
        </div>

        <div class="ui segment">
          <h2 class="ui header">
            <i class="red frown outline icon"></i>
            <div class="content">
              {{ overdue_n }}
              <div class="sub header">Behind schedule</div>
            </div>
          </h2>
        </div>
      </div>
    </div>

    <div class="ui stackable four column grid">
      <div class="five wide column">
        <div class="ui stacked segments">
          <div class="ui header large segment">Tasks Overview</div>

          <div class="ui segment">
            <h2 class="ui header">
              <i class="calendar icon"></i>
              <div class="content">
                {{ tasks_n }}
                <div class="sub header">Tasks Open</div>
              </div>
            </h2>

            <div class="ui circular labels">
              <div class="ui horizontal list">
                <div class="item"><a class="ui green label spaced">{{ tasks_n_complete }}</a> Completed</div>
                <div class="item"><a class="ui yellow label spaced">{{ tasks_n_pending }}</a> Pending</div>
              </div> 
            </div>
          </div>
        </div>
      </div>
      <div class="eleven wide column">
        <div class="ui stacked segments">
          <div class="ui header large segment">Current Pending Projects</div>

          <div class="ui segment">
            <div class="ui divided items">
              {% for project in current_projects %}
                <div class="item">
                  <div class="ui tiny image">
                    <img src="{% static 'img/projects/'|add:project.icon %}">
                  </div>

                  <div class="middle aligned content">
                    <a href="{% url 'detail_project' project.id %}" class="header floated left">{{ project.name }}</a>
                    
                    <div class="ui teal label" style="margin-left: 1em;">
                      <i class="clock icon"></i>{{ project.due_date|timeuntil }} left
                    </div>

                    <a class="ui blue image label">
                      <img src="{% static 'img/avatars/'|add:project.leader.employeeprofile.picture %}">
                      {{ project.leader.first_name }}
                      <div class="detail">Team Leader</div>
                    </a>

                    <div class="description">
                      <p>{{ project.description }}</p>
                    </div>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script>$('.ui.dropdown').dropdown()</script>
{% endblock script %}

parrasoft/templates/home/detail_project.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ project.name }} Details{% endblock %}

{% block content %}
  {% include 'components/main_menu.html' %}

  <div class="ui container">
    <div class="ui text container" style="margin-bottom: 1em;">
      <h1 class="ui center aligned header">
        <img src="{% static 'img/projects/'|add:project.icon %}" class="ui rounded large image">
        <div class="content">{{ project.name }}</div>

        <div class="ui tiny three item menu">
          <a class="item"><i class="github icon"></i> Repository</a>
          <a class="item"><i class="pencil icon"></i> Edit Project</a>
          <a class="item"><i class="plus circle icon"></i> Add Activity</a>
        </div>

        <p class="sub header">{{ project.description }}</p>
      </h1>
    </div>

    <div class="ui blue progress small" data-percent="{{ percentage }}" id="proj-progress">
      <div class="bar"></div>
    </div>


    <div class="ui three stackable cards">
      {% for activity in project.activity_set.all %}
        <div class="card">
          <div class="content">
            <i class="right floated check icon"></i>
            <i class="right floated trash icon"></i>

            <div class="header">{{ activity.title }}</div>

            <div class="description">
              {{ activity.description }}
            </div>

            <div class="ui label" style="margin-top:1em;">
              <i class="bell outline icon"></i>
              Deadline: <span class="detail">{{ activity.deadline }}</span>
            </div>

            <h4 class="ui sub header">Tasks to complete</h4>
            <div class="ui middle aligned selection list">
              {% for task in activity.task_set.all %}
                <div class="item">
                  <div class="content">
                    {% if task.completed %}
                      <i class="blue check square icon"></i>
                    {% else %}
                      <i class="toggle square outline icon"></i>
                    {% endif %}
                    <a style="color:#555;" href="#">{{ task.title }}</a>
                  </div>
                </div>
              {% endfor %}
            </div>
          </div>

          <div class="extra content">
            <div class="ui large transparent left icon input">
              <i class="sitemap icon"></i>
              <input type="text" placeholder="Add a new task...">
            </div>
          </div>

          <div class="ui bottom attached button">
            <i class="pencil icon"></i> Edit Activity
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

{% block script %}
  <script>
    $('.ui.dropdown').dropdown()
    $('#proj-progress').progress();
  </script>
{% endblock script %}

parrasoft/templates/home/landing.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Welcome!{% endblock title %}

{% block content %}
  {% include 'components/anon_menu.html' %}

  <div class="ui text container center aligned">
    <h1 class="ui header" style="font-size: 4em;"><img src="{% static 'img/logo.png' %}" alt="logo"> ParraSoft</h1>
    <h3 class="ui grey header">Leading software development company in Mexico. We harbor some of the best talents ranging from immensely talented graphic designers to user experience veterans, seasoned game developers and battle-tested programmers.</h3>
    <div class="ui huge primary button">Employee Sign Up <i class="right arrow icon"></i></div>
  </div>

  <div class="ui container" style="margin-top: 2em;">
    <div class="ui horizontal segments">
      <div class="ui segment">
        <h2 class="ui icon header">
          <i class="paper plane icon"></i>
          <div class="content">
            Fast delivery
            <div class="sub header">We're always trying to deliver our projects as fast and reliably as possible without sacrificing quality and effort.</div>
          </div>
        </h2>
      </div>
      <div class="ui left aligned segment">
        <h2 class="ui icon header">
          <i class="dollar sign icon"></i>
          <div class="content">
            Affordable
            <div class="sub header">Our projects are affordable for every type of customer and budget. Just give us a call and let's make business together!</div>
          </div>
        </h2>
      </div>
      <div class="ui left aligned segment">
        <h2 class="ui icon header">
          <i class="rocket icon"></i>
          <div class="content">
            Cutting Edge Tech
            <div class="sub header">We strive to use the latest technology for you, unless you specify the compatibility of your choice. Our goal is to build quality, scalable and durable software.</div>
          </div>
        </h2>
      </div>
    </div>
  </div>

  <!-- Modal for Login Form -->
  <div class="ui mini modal" id="login-modal">
    <div class="header">Log In as Employee</div>
    <div class="content">
      {% if form.non_field_errors %}
        <div class="ui error message">
          <i class="close icon"></i>
          <div class="header">
            There were some errors with your submission
          </div>
          <ul class="list">
            {% for error in form.non_field_errors %}
              <li>{{ error }}</li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}

      <form action="{% url 'login_view' %}" method="post" id="login_form" class="ui form">
        {% csrf_token %}

        {% for field in form %}
          <div class="field">
            {{ field.errors }}
            <label>{{ field.label_tag }}</label>
            {{ field }}
          </div>
        {% endfor %}

        <div class="actions">
          <a id="close-form" class="ui button">Cancel</a>
          <button id="submit-btn" class="ui black button" type="submit">Log In</button>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

{% block script %}
  <script>
    $('#login-modal').modal('attach events', '#login-btn', 'show')
    $('#login-modal').modal('attach events', '#close-form', 'hide')

    $('.message .close').on('click', function() {
      $(this).closest('.message').transition('fade')
    })

    $('#login_form').on('submit', function(e) {
      $('#submit-btn').addClass('loading').prop('disabled', true)
    })
  </script>
{% endblock script %}

parrasoft/templates/home/update_project.html
{% extends "base.html" %}
{% load static %}

{% block title %}Update Project Details{% endblock %}

{% block content %}
  {% include 'components/main_menu.html' %}

  <div class="ui container">
    <h1 class="ui header">
      <img src="{% static 'img/projects/'|add:form.instance.icon %}" class="ui circular image">
      Updating {{ form.instance.name }}
    </h1>

    <form class="ui form" method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div class="field">
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
        </div>
      {% endfor %}

      <button type="submit" class="ui button">Update</button>
    </form>
  </div>
{% endblock %}

{% block script %}
  <script>$('.ui.dropdown').dropdown()</script>
{% endblock script %}

parrasoft/templates/home/update_task.html
{% extends "base.html" %}
{% load static %}

{% block title %}Update Task{% endblock %}

{% block content %}
  {% include 'components/main_menu.html' %}

  <div class="ui container">
    <h1 class="ui header">
      Updating {{ form.instance.title }}
    </h1>

    <form class="ui form" method="POST">
      {% csrf_token %}

      {% for field in form %}
        <div class="field">
          {{ field.errors }}
          {{ field.label_tag }} {{ field }}
        </div>
      {% endfor %}

      <button type="submit" class="ui button">Update task</button>
    </form>
  </div>
{% endblock %}